//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TodoWCFService.Models
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TodoItem", Namespace="http://schemas.datacontract.org/2004/07/TodoWCFService.Models")]
    public partial class TodoItem : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private bool DoneField;
        
        private string IDField;
        
        private string NameField;
        
        private string NotesField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Done
        {
            get
            {
                return this.DoneField;
            }
            set
            {
                this.DoneField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ID
        {
            get
            {
                return this.IDField;
            }
            set
            {
                this.IDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name
        {
            get
            {
                return this.NameField;
            }
            set
            {
                this.NameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Notes
        {
            get
            {
                return this.NotesField;
            }
            set
            {
                this.NotesField = value;
            }
        }
    }
}


[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(ConfigurationName="ITodoService")]
public interface ITodoService
{
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITodoService/GetTodoItems", ReplyAction="http://tempuri.org/ITodoService/GetTodoItemsResponse")]
    TodoWCFService.Models.TodoItem[] GetTodoItems();
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITodoService/GetTodoItems", ReplyAction="http://tempuri.org/ITodoService/GetTodoItemsResponse")]
    System.Threading.Tasks.Task<TodoWCFService.Models.TodoItem[]> GetTodoItemsAsync();
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITodoService/CreateTodoItem", ReplyAction="http://tempuri.org/ITodoService/CreateTodoItemResponse")]
    void CreateTodoItem(TodoWCFService.Models.TodoItem item);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITodoService/CreateTodoItem", ReplyAction="http://tempuri.org/ITodoService/CreateTodoItemResponse")]
    System.Threading.Tasks.Task CreateTodoItemAsync(TodoWCFService.Models.TodoItem item);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITodoService/EditTodoItem", ReplyAction="http://tempuri.org/ITodoService/EditTodoItemResponse")]
    void EditTodoItem(TodoWCFService.Models.TodoItem item);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITodoService/EditTodoItem", ReplyAction="http://tempuri.org/ITodoService/EditTodoItemResponse")]
    System.Threading.Tasks.Task EditTodoItemAsync(TodoWCFService.Models.TodoItem item);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITodoService/DeleteTodoItem", ReplyAction="http://tempuri.org/ITodoService/DeleteTodoItemResponse")]
    void DeleteTodoItem(string id);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITodoService/DeleteTodoItem", ReplyAction="http://tempuri.org/ITodoService/DeleteTodoItemResponse")]
    System.Threading.Tasks.Task DeleteTodoItemAsync(string id);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITodoService/UsernamePatternMatch", ReplyAction="http://tempuri.org/ITodoService/UsernamePatternMatchResponse")]
    bool UsernamePatternMatch(string username);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITodoService/UsernamePatternMatch", ReplyAction="http://tempuri.org/ITodoService/UsernamePatternMatchResponse")]
    System.Threading.Tasks.Task<bool> UsernamePatternMatchAsync(string username);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITodoService/PasswordPatternMatch", ReplyAction="http://tempuri.org/ITodoService/PasswordPatternMatchResponse")]
    bool PasswordPatternMatch(string username);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITodoService/PasswordPatternMatch", ReplyAction="http://tempuri.org/ITodoService/PasswordPatternMatchResponse")]
    System.Threading.Tasks.Task<bool> PasswordPatternMatchAsync(string username);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITodoService/EmailPatternMatch", ReplyAction="http://tempuri.org/ITodoService/EmailPatternMatchResponse")]
    bool EmailPatternMatch(string username);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITodoService/EmailPatternMatch", ReplyAction="http://tempuri.org/ITodoService/EmailPatternMatchResponse")]
    System.Threading.Tasks.Task<bool> EmailPatternMatchAsync(string username);
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public interface ITodoServiceChannel : ITodoService, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class TodoServiceClient : System.ServiceModel.ClientBase<ITodoService>, ITodoService
{
    
    public TodoServiceClient()
    {
    }
    
    public TodoServiceClient(string endpointConfigurationName) : 
            base(endpointConfigurationName)
    {
    }
    
    public TodoServiceClient(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public TodoServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public TodoServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    public TodoWCFService.Models.TodoItem[] GetTodoItems()
    {
        return base.Channel.GetTodoItems();
    }
    
    public System.Threading.Tasks.Task<TodoWCFService.Models.TodoItem[]> GetTodoItemsAsync()
    {
        return base.Channel.GetTodoItemsAsync();
    }
    
    public void CreateTodoItem(TodoWCFService.Models.TodoItem item)
    {
        base.Channel.CreateTodoItem(item);
    }
    
    public System.Threading.Tasks.Task CreateTodoItemAsync(TodoWCFService.Models.TodoItem item)
    {
        return base.Channel.CreateTodoItemAsync(item);
    }
    
    public void EditTodoItem(TodoWCFService.Models.TodoItem item)
    {
        base.Channel.EditTodoItem(item);
    }
    
    public System.Threading.Tasks.Task EditTodoItemAsync(TodoWCFService.Models.TodoItem item)
    {
        return base.Channel.EditTodoItemAsync(item);
    }
    
    public void DeleteTodoItem(string id)
    {
        base.Channel.DeleteTodoItem(id);
    }
    
    public System.Threading.Tasks.Task DeleteTodoItemAsync(string id)
    {
        return base.Channel.DeleteTodoItemAsync(id);
    }
    
    public bool UsernamePatternMatch(string username)
    {
        return base.Channel.UsernamePatternMatch(username);
    }
    
    public System.Threading.Tasks.Task<bool> UsernamePatternMatchAsync(string username)
    {
        return base.Channel.UsernamePatternMatchAsync(username);
    }
    
    public bool PasswordPatternMatch(string username)
    {
        return base.Channel.PasswordPatternMatch(username);
    }
    
    public System.Threading.Tasks.Task<bool> PasswordPatternMatchAsync(string username)
    {
        return base.Channel.PasswordPatternMatchAsync(username);
    }
    
    public bool EmailPatternMatch(string username)
    {
        return base.Channel.EmailPatternMatch(username);
    }
    
    public System.Threading.Tasks.Task<bool> EmailPatternMatchAsync(string username)
    {
        return base.Channel.EmailPatternMatchAsync(username);
    }
}
