//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Foosball_Lib.Models {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Labels {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Labels() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Foosball_Lib.Models.Labels", typeof(Labels).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email doesn not match pattern , please repeat.
        /// </summary>
        internal static string EmailNotMatch {
            get {
                return ResourceManager.GetString("EmailNotMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed.
        /// </summary>
        internal static string Failed {
            get {
                return ResourceManager.GetString("Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Goal Limit has not been assigned.
        /// </summary>
        internal static string GoalLimit {
            get {
                return ResourceManager.GetString("GoalLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        internal static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login succesful.
        /// </summary>
        internal static string LoginSucc {
            get {
                return ResourceManager.GetString("LoginSucc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MatchHistory.txt.
        /// </summary>
        internal static string MatchHistory {
            get {
                return ResourceManager.GetString("MatchHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Limit.
        /// </summary>
        internal static string NoLimit {
            get {
                return ResourceManager.GetString("NoLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password or username doesnt match pattern(or empty).
        /// </summary>
        internal static string NoMatch {
            get {
                return ResourceManager.GetString("NoMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No opponent.
        /// </summary>
        internal static string NoOp {
            get {
                return ResourceManager.GetString("NoOp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        internal static string Ok {
            get {
                return ResourceManager.GetString("Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opponent name doesnt match pattern(or empty).
        /// </summary>
        internal static string OpNameNotMatch {
            get {
                return ResourceManager.GetString("OpNameNotMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You haven&apos;t choosen your opponent.
        /// </summary>
        internal static string OpNotChosen {
            get {
                return ResourceManager.GetString("OpNotChosen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passwords do not match, please repeat.
        /// </summary>
        internal static string PassNotMatch {
            get {
                return ResourceManager.GetString("PassNotMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Player .
        /// </summary>
        internal static string Player {
            get {
                return ResourceManager.GetString("Player", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registration.
        /// </summary>
        internal static string Registration {
            get {
                return ResourceManager.GetString("Registration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registration was succesful!.
        /// </summary>
        internal static string RegSucc {
            get {
                return ResourceManager.GetString("RegSucc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This user already exists!.
        /// </summary>
        internal static string UserExists {
            get {
                return ResourceManager.GetString("UserExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This user does not exist!.
        /// </summary>
        internal static string UserNotExists {
            get {
                return ResourceManager.GetString("UserNotExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UsersList.txt.
        /// </summary>
        internal static string UsersList {
            get {
                return ResourceManager.GetString("UsersList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Win.
        /// </summary>
        internal static string Win {
            get {
                return ResourceManager.GetString("Win", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  won the game!.
        /// </summary>
        internal static string WonGame {
            get {
                return ResourceManager.GetString("WonGame", resourceCulture);
            }
        }
    }
}
